name: ci

on:
  workflow_dispatch:
  
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3 
      -
        name: Vulnerability scan of terraform configration file
        run: snyk terraform test
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
